### ISSUE TITLE
Pully cannot find module m3u8stream/lib/parse-time

### ISSUE THREAD

**Issue by emdCatalyst** [JimmyBoh/pully#38] opened 2020-06-17 13:56 UTC
Pully cannot find m3u8stream/lib/parse-time although i installed the latest version of pully and ytdl-core:
  "pully": "^2.7.0",
  "pully-core": "^0.9.1",
  "ytdl-core": "^2.1.7"
Any help would be appreciated :)

**Comment by jimbuck** [comment] 2020-06-18 12:49
This appears to be a duplicate of #36, closing this in favor of continuing in that thread.

**Closed as completed by jimbuck** 2020-06-18 12:49 UTC

**Comment by emdCatalyst** [comment] 2020-06-30 19:20
i mentioned the versions, the opposed original issue mentions that the issue was fixed in the version im using but does not seem to be true.
