### ISSUE TITLE
Lib throws: Error: Cannot find module 'm3u8stream/lib/parse-time'

### ISSUE THREAD

**Issue by Sten435** [JimmyBoh/pully#42] opened 2020-12-17 13:13 UTC
```
const { Pully, Presets } = require('pully')

const pully = new Pully();

async function x(){
const video = await pully.query('https://www.youtube.com/watch?v=RvYYCGs45L4');
console.log(`${video.videoTitle} by ${video.channelName} has ${video.views} views!`);

const options = {
  url: 'https://www.youtube.com/watch?v=RvYYCGs45L4',
  preset: Presets.FourK,
  progress: (data) => console.log(data.percent + '%') // Progress reporter callback...
};

const { path, format, duration } = await pully.download(options);
console.log(path);     // Path to the downloaded file.
console.log(format);   // Object containing all audio/video/meta data.
console.log(duration); // Number of milliseconds the download took.
}

x()
```

**internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'm3u8stream/lib/parse-time'
Require stack:
- /Users/stanpersoons/Documents/Electron/Test/node_modules/ytdl-core/lib/index.js
- /Users/stanpersoons/Documents/Electron/Test/node_modules/pully-core/dist/index.js
- /Users/stanpersoons/Documents/Electron/Test/node_modules/pully/dist/index.js
- /Users/stanpersoons/Documents/Electron/Test/node_modules/pully/index.js
- /Users/stanpersoons/Documents/Electron/Test/app.js**

**Comment by jimbuck** [comment] 2020-12-18 03:18
This appears to be a duplicate of #36. I don't have time to fix this now but there are workarounds in the discussion there.

**Closed as completed by jimbuck** 2020-12-18 03:18 UTC
