### ISSUE TITLE
Pully is not downloading videos. I am using it alongside ytdl-core

### ISSUE THREAD

**Issue by matifzia** [JimmyBoh/pully#55] opened 2024-02-19 08:39 UTC
Hi, I am using ytdl-core with ffmpeg on Nest.js server. I use ffmpeg to merge the Audio/video streams that works fine on 720p,1080p. The 360p is already providing audio that's fine. But on more higher resolution like 1440p and 2160p it is not working. in fact it's on('finish') event is never called for 1440 and 2160. due to what audio/video merging never successful. There is any way to handle it. I already seen pully https://www.npmjs.com/package/pully but pully is not working as well.

 const options: DownloadConfig = {
        url: videoUrl,
        preset:Presets.TwoK,,
        progress: (data) => {
          this.progressEmitter.emit('download-progress', data.percent);
        },
      };

      return new Promise((resolve, reject) => {
        pully
          .download(options)
          .then((res) => {
            console.log('RES : ', res.path);

            resolve(res.path);
          })
          .catch((err) => {
            console.log('Error : ', err);
            reject(err);
          });
      });

this code is always giving error something like player not found and sometimes says cannot find module m3u8stream\lib\parse-time.js. Here is my packages

"pully": "^2.7.0"
"ytdl-core": "^4.11.5"

**Comment by matifzia** [comment] 2024-02-28 05:30
It is maintained or not?

**Comment by jimbuck** [comment] 2024-03-20 14:34
Not actively, but I have started working on updating the library (and merging the related repos into one monorepo). I can't give any promises on when it will be updated, but it is in progress.

In the meantime, you could try the workarounds mention in [this StackOverflow question](https://stackoverflow.com/questions/58965713/cannot-find-module-m3u8stream-lib-parse-time), or [try installing the latest version of `node-ytdl-core`](https://github.com/fent/node-ytdl-core/issues/531).

**Comment by jimbuck** [comment] 2024-03-20 14:36
Closing as duplicate of #36.

**Closed as not planned by jimbuck** 2024-03-20 14:36 UTC
